project:
  type: book
  output-dir: docs
book:
  title: "Geocomputation with Python"
  number-sections: true
  author: "Michael Dorman, Anita Graser, Jakub Nowosad, Robin Lovelace"
  description: | 
    An introductory yet rigorous and maintained resource on working with geographic data in Python ðŸŽ‰
  #cover-image: https://geocompr.robinlovelace.net/images/cover.png
  site-url: https://py.geocomp.xyz
  repo-url: https://github.com/geocompr/py/
  repo-branch: main
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - 02-spatial-data.qmd
    - 03-attribute-operations.qmd
    - 04-spatial-operations.qmd
    - 05-geometry-operations.qmd
    - 06-raster-vector.qmd
    - 07-reproj.qmd
    - 08-read-write-plot.qmd
    - 09-mapping.qmd
format:
  html: 
    theme: flatly
    #cover-image: https://geocompr.robinlovelace.net/images/cover.png
    code-link: true
    template-partials: toc.html
    toc-title: "On this page"
    code-overflow: wrap
    toc-depth: 4
# jupyter: python3
