project:
  type: book
  output-dir: docs

book:
  title: "Geocomputation with Python"
  page-footer: "Geocomputation with Python was written by Michael Dorman, Anita Graser, Jakub Nowosad, and Robin Lovelace."
  # number-sections: true
  author: "Michael Dorman, Anita Graser, Jakub Nowosad, Robin Lovelace"
  description: | 
    An introductory resource for working with geographic data in Python
  cover-image: https://geocompx.org/static/img/book_cover_py_tmp_small.png
  site-url: https://py.geocompx.org
  repo-url: https://github.com/geocompx/geocompy/
  repo-branch: main
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  google-analytics: G-ZEMGTY4VV3
  chapters:
    - index.qmd
    - preface.qmd
    - 01-spatial-data.qmd
    - 02-attribute-operations.qmd
    - 03-spatial-operations.qmd
    - 04-geometry-operations.qmd
    - 05-raster-vector.qmd
    - 06-reproj.qmd
    - 07-read-write.qmd
    - 08-mapping.qmd
    - references.qmd

format:
  html: 
    theme: flatly
    code-link: true
    template-partials: [helpers/toc.html, helpers/title-block.html]
    toc-title: "On this page"
    code-overflow: wrap
    toc-depth: 4
  # pdf:
  #   documentclass: krantz
  #   monofont: 'Source Code Pro'
  #   monofontoptions: 
  #     - Scale=0.7
  #   pdf-engine: xelatex
  #   keep-tex: true
  #   number-sections: true
  #   top-level-division: chapter
  #   include-before-body: helpers/before_body.tex
  #   include-in-header: 
  #     text: |
  #       \AtBeginEnvironment{longtable}{\footnotesize}
  #       \usepackage{makeidx}
  #       \usepackage{gensymb}
  #       \makeindex
  #   include-after-body: 
  #     text: |
  #       \printindex

jupyter: python3
bibliography: geocompr.bib
