project:
  type: book
  output-dir: docs
  
book:
  title: "Geocomputation with Python"
  # author: "TBC"
  description: | 
    Work in Progress ðŸŽ‰
  #cover-image: https://geocompr.robinlovelace.net/images/cover.png
  site-url: https://geocompr.github.io
  repo-url: https://github.com/geocompr/py/
  repo-branch: main
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - 02-spatial-data.qmd
    - 03-attribute-operations.qmd
    - 04-spatial-operations.qmd
    - 05-geometry-operations.qmd
    - 06-raster-vector.qmd
    - 07-reproj.qmd
    - 08-read-write-plot.qmd
    - 09-mapping.qmd
  appendices:
    - a1-starting.qmd
format:
  html: 
    theme: cosmo
    #cover-image: https://geocompr.robinlovelace.net/images/cover.png
    code-link: true
