name: geocompy
channels:
  - conda-forge
  - default
dependencies:
  - python=3.9
  - bokeh
  - cartopy==0.19.0
  - cython
  - folium
  - geopandas
  - geopy
  - pygeos
  - geoviews
  - hvplot
  - jupyter
  - jupyterlab
  - matplotlib
  - nbformat
  - numpy
  - pandas
  - proj
  - rasterio
  - shapely
  - topojson
  - mapclassify
  - rasterstats
