on:
  push:
    branches:
      [main]
name: Render
jobs:
  bookdown:
    name: GH-Pages
    runs-on: ubuntu-latest
    container: geocompr/geocompr:conda
    defaults:
      run:
        shell: bash -l {0}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Render
        run: |
          conda env list
          conda activate geocompy
          ./convert.sh
          # test code:
          for f in ipynb/*.ipynb; do jupyter nbconvert --execute --to html "$f"; done
          quarto render
          ls docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          commit_message: 'Deploy commit: ${{ github.event.head_commit.message }}'
